### ISSUE TITLE
Fork me on github ribbon

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/ocr-transform#18]

**Comment by zuphilip** [comment]
Does this looks nice also when changing the size of the window? I tried this also out before committing such a link just in the help https://github.com/UB-Mannheim/ocr-transform/commit/143159a86184bb3a172f2316fe96ff6fa6d88ed3

**Comment by kba** [comment]
I tweaked it to hide the ribbon for smaller/mobile devices. Or do you think it looks bad for large devices? That can be adapted with [Bootstrap's helper classes](http://getbootstrap.com/css/#responsive-utilities).

**Comment by kba** [comment]
https://github.com/UB-Mannheim/ocr-transform/commit/143159a86184bb3a172f2316fe96ff6fa6d88ed3 :+1: for a textual link anyway.

**Comment by zuphilip** [comment]
It looked critical on smaller window sizes. Thus, I guess that hiding the ribbon for smaller/mobile devices solves this problem. Fine, for me me now.
